language: scala

sudo: required

before_script:
- openssl aes-256-cbc -K $encrypted_b1201882d542_key -iv $encrypted_b1201882d542_iv -in secrets.tar.gz.enc -out secrets.tar.gz -d
- tar zxf secrets.tar.gz

script:
- |
  if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    sbt 'set isSnapshot := false' 'set version := IO.read(new File("VERSION")).mkString.trim' test +publishSigned
  elif [[ "$TRAVIS_BRANCH" == "develop" ]]; then
    sbt -no-colors test +publishSigned
  else
    sbt -no-colors test
  fi

# Don't build version tags
branches:
  except:
    - /^v[0-9]+\.[0-9]{1,2}\.[0-9]{1,2}$/
