name: SBT CI

on:
  push:
    branches:
      - '*'
      - '!v**'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier
          key: global-sbt-cache
      - name: Setup GPG
        run: |
          echo "$PUBLIC_GPG_KEY" > public.key
          echo "$PRIVATE_GPG_KEY" > private.key
          echo "$OSS_NEXUS_CREDENTIALS" > nexus.credentials
          echo "PGP_PASS=$GPG_OPENSOURCE_PASS" >> "$GITHUB_ENV"
          ls .
        shell: bash
        env:
          PUBLIC_GPG_KEY: ${{secrets.OSS_PUBLIC_GPG_KEY}}
          PRIVATE_GPG_KEY: ${{secrets.OSS_PRIVATE_GPG_KEY}}
          OSS_NEXUS_CREDENTIALS: ${{secrets.OSS_NEXUS_CREDENTIALS}}
          GPG_OPENSOURCE_PASS: ${{secrets.OSS_PGP_PASS}}
      - name: Sbt test
        if: ${{github.ref_name != 'master'}}
        run: sbt test
      - name: Sbt deploy
#        if: ${{github.ref_name == 'master'}}
        run: sbt 'set isSnapshot := false' 'set version := IO.read(new File("VERSION")).mkString.trim' test +publishSigned
